language: ruby
cache: bundler
install: gem install bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build tba-api-client-ruby.gemspec
  - gem install ./tba-api-client-ruby-1.0.0.gem
