=begin
#The Blue Alliance API v3

## Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.

OpenAPI spec version: 3.03.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::EventApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'EventApi' do
  before do
    # run before each test
    @instance = SwaggerClient::EventApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EventApi' do
    it 'should create an instance of EventApi' do
      expect(@instance).to be_instance_of(SwaggerClient::EventApi)
    end
  end

  # unit tests for get_district_events
  # 
  # Gets a list of events in the given district.
  # @param district_key TBA District Key, eg &#x60;2016fim&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<Event>]
  describe 'get_district_events test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_district_events_keys
  # 
  # Gets a list of event keys for events in the given district.
  # @param district_key TBA District Key, eg &#x60;2016fim&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<String>]
  describe 'get_district_events_keys test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_district_events_simple
  # 
  # Gets a short-form list of events in the given district.
  # @param district_key TBA District Key, eg &#x60;2016fim&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<EventSimple>]
  describe 'get_district_events_simple test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event
  # 
  # Gets an Event.
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Event]
  describe 'get_event test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event_alliances
  # 
  # Gets a list of Elimination Alliances for the given Event.
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<EliminationAlliance>]
  describe 'get_event_alliances test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event_awards
  # 
  # Gets a list of awards from the given event.
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<Award>]
  describe 'get_event_awards test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event_district_points
  # 
  # Gets a list of team rankings for the Event.
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [EventDistrictPoints]
  describe 'get_event_district_points test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event_insights
  # 
  # Gets a set of Event-specific insights for the given Event.
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [EventInsights]
  describe 'get_event_insights test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event_match_timeseries
  # 
  # Gets an array of Match Keys for the given event key that have timeseries data. Returns an empty array if no matches have timeseries data. *WARNING:* This is *not* official data, and is subject to a significant possibility of error, or missing data. Do not rely on this data for any purpose. In fact, pretend we made it up. *WARNING:* This endpoint and corresponding data models are under *active development* and may change at any time, including in breaking ways.
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<String>]
  describe 'get_event_match_timeseries test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event_matches
  # 
  # Gets a list of matches for the given event.
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<Match>]
  describe 'get_event_matches test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event_matches_keys
  # 
  # Gets a list of match keys for the given event.
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<String>]
  describe 'get_event_matches_keys test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event_matches_simple
  # 
  # Gets a short-form list of matches for the given event.
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<MatchSimple>]
  describe 'get_event_matches_simple test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event_op_rs
  # 
  # Gets a set of Event OPRs (including OPR, DPR, and CCWM) for the given Event.
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [EventOPRs]
  describe 'get_event_op_rs test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event_predictions
  # 
  # Gets information on TBA-generated predictions for the given Event. Contains year-specific information. *WARNING* This endpoint is currently under development and may change at any time.
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [EventPredictions]
  describe 'get_event_predictions test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event_rankings
  # 
  # Gets a list of team rankings for the Event.
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [EventRanking]
  describe 'get_event_rankings test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event_simple
  # 
  # Gets a short-form Event.
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [EventSimple]
  describe 'get_event_simple test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event_teams
  # 
  # Gets a list of &#x60;Team&#x60; objects that competed in the given event.
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<Team>]
  describe 'get_event_teams test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event_teams_keys
  # 
  # Gets a list of &#x60;Team&#x60; keys that competed in the given event.
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<String>]
  describe 'get_event_teams_keys test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event_teams_simple
  # 
  # Gets a short-form list of &#x60;Team&#x60; objects that competed in the given event.
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<TeamSimple>]
  describe 'get_event_teams_simple test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event_teams_statuses
  # 
  # Gets a key-value list of the event statuses for teams competing at the given event.
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Hash<String, TeamEventStatus>]
  describe 'get_event_teams_statuses test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_events_by_year
  # 
  # Gets a list of events in the given year.
  # @param year Competition Year (or Season). Must be 4 digits.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<Event>]
  describe 'get_events_by_year test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_events_by_year_keys
  # 
  # Gets a list of event keys in the given year.
  # @param year Competition Year (or Season). Must be 4 digits.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<String>]
  describe 'get_events_by_year_keys test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_events_by_year_simple
  # 
  # Gets a short-form list of events in the given year.
  # @param year Competition Year (or Season). Must be 4 digits.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<EventSimple>]
  describe 'get_events_by_year_simple test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_team_event_awards
  # 
  # Gets a list of awards the given team won at the given event.
  # @param team_key TBA Team Key, eg &#x60;frc254&#x60;
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<Award>]
  describe 'get_team_event_awards test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_team_event_matches
  # 
  # Gets a list of matches for the given team and event.
  # @param team_key TBA Team Key, eg &#x60;frc254&#x60;
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<Match>]
  describe 'get_team_event_matches test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_team_event_matches_keys
  # 
  # Gets a list of match keys for matches for the given team and event.
  # @param team_key TBA Team Key, eg &#x60;frc254&#x60;
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<String>]
  describe 'get_team_event_matches_keys test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_team_event_matches_simple
  # 
  # Gets a short-form list of matches for the given team and event.
  # @param team_key TBA Team Key, eg &#x60;frc254&#x60;
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<Match>]
  describe 'get_team_event_matches_simple test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_team_event_status
  # 
  # Gets the competition rank and status of the team at the given event.
  # @param team_key TBA Team Key, eg &#x60;frc254&#x60;
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [TeamEventStatus]
  describe 'get_team_event_status test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_team_events
  # 
  # Gets a list of all events this team has competed at.
  # @param team_key TBA Team Key, eg &#x60;frc254&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<Event>]
  describe 'get_team_events test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_team_events_by_year
  # 
  # Gets a list of events this team has competed at in the given year.
  # @param team_key TBA Team Key, eg &#x60;frc254&#x60;
  # @param year Competition Year (or Season). Must be 4 digits.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<Event>]
  describe 'get_team_events_by_year test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_team_events_by_year_keys
  # 
  # Gets a list of the event keys for events this team has competed at in the given year.
  # @param team_key TBA Team Key, eg &#x60;frc254&#x60;
  # @param year Competition Year (or Season). Must be 4 digits.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<String>]
  describe 'get_team_events_by_year_keys test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_team_events_by_year_simple
  # 
  # Gets a short-form list of events this team has competed at in the given year.
  # @param team_key TBA Team Key, eg &#x60;frc254&#x60;
  # @param year Competition Year (or Season). Must be 4 digits.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<EventSimple>]
  describe 'get_team_events_by_year_simple test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_team_events_keys
  # 
  # Gets a list of the event keys for all events this team has competed at.
  # @param team_key TBA Team Key, eg &#x60;frc254&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<String>]
  describe 'get_team_events_keys test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_team_events_simple
  # 
  # Gets a short-form list of all events this team has competed at.
  # @param team_key TBA Team Key, eg &#x60;frc254&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<EventSimple>]
  describe 'get_team_events_simple test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_team_events_statuses_by_year
  # 
  # Gets a key-value list of the event statuses for events this team has competed at in the given year.
  # @param team_key TBA Team Key, eg &#x60;frc254&#x60;
  # @param year Competition Year (or Season). Must be 4 digits.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Hash<String, TeamEventStatus>]
  describe 'get_team_events_statuses_by_year test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
