=begin
#The Blue Alliance API v3

## Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.

OpenAPI spec version: 3.03.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ListApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ListApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ListApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ListApi' do
    it 'should create an instance of ListApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ListApi)
    end
  end

  # unit tests for get_district_events
  # 
  # Gets a list of events in the given district.
  # @param district_key TBA District Key, eg &#x60;2016fim&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<Event>]
  describe 'get_district_events test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_district_events_keys
  # 
  # Gets a list of event keys for events in the given district.
  # @param district_key TBA District Key, eg &#x60;2016fim&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<String>]
  describe 'get_district_events_keys test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_district_events_simple
  # 
  # Gets a short-form list of events in the given district.
  # @param district_key TBA District Key, eg &#x60;2016fim&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<EventSimple>]
  describe 'get_district_events_simple test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_district_rankings
  # 
  # Gets a list of team district rankings for the given district.
  # @param district_key TBA District Key, eg &#x60;2016fim&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<DistrictRanking>]
  describe 'get_district_rankings test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_district_teams
  # 
  # Gets a list of &#x60;Team&#x60; objects that competed in events in the given district.
  # @param district_key TBA District Key, eg &#x60;2016fim&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<Team>]
  describe 'get_district_teams test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_district_teams_keys
  # 
  # Gets a list of &#x60;Team&#x60; objects that competed in events in the given district.
  # @param district_key TBA District Key, eg &#x60;2016fim&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<String>]
  describe 'get_district_teams_keys test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_district_teams_simple
  # 
  # Gets a short-form list of &#x60;Team&#x60; objects that competed in events in the given district.
  # @param district_key TBA District Key, eg &#x60;2016fim&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<TeamSimple>]
  describe 'get_district_teams_simple test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event_teams
  # 
  # Gets a list of &#x60;Team&#x60; objects that competed in the given event.
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<Team>]
  describe 'get_event_teams test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event_teams_keys
  # 
  # Gets a list of &#x60;Team&#x60; keys that competed in the given event.
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<String>]
  describe 'get_event_teams_keys test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event_teams_simple
  # 
  # Gets a short-form list of &#x60;Team&#x60; objects that competed in the given event.
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<TeamSimple>]
  describe 'get_event_teams_simple test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event_teams_statuses
  # 
  # Gets a key-value list of the event statuses for teams competing at the given event.
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Hash<String, TeamEventStatus>]
  describe 'get_event_teams_statuses test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_events_by_year
  # 
  # Gets a list of events in the given year.
  # @param year Competition Year (or Season). Must be 4 digits.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<Event>]
  describe 'get_events_by_year test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_events_by_year_keys
  # 
  # Gets a list of event keys in the given year.
  # @param year Competition Year (or Season). Must be 4 digits.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<String>]
  describe 'get_events_by_year_keys test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_events_by_year_simple
  # 
  # Gets a short-form list of events in the given year.
  # @param year Competition Year (or Season). Must be 4 digits.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<EventSimple>]
  describe 'get_events_by_year_simple test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_team_events_statuses_by_year
  # 
  # Gets a key-value list of the event statuses for events this team has competed at in the given year.
  # @param team_key TBA Team Key, eg &#x60;frc254&#x60;
  # @param year Competition Year (or Season). Must be 4 digits.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Hash<String, TeamEventStatus>]
  describe 'get_team_events_statuses_by_year test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_teams
  # 
  # Gets a list of &#x60;Team&#x60; objects, paginated in groups of 500.
  # @param page_num Page number of results to return, zero-indexed
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<Team>]
  describe 'get_teams test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_teams_by_year
  # 
  # Gets a list of &#x60;Team&#x60; objects that competed in the given year, paginated in groups of 500.
  # @param year Competition Year (or Season). Must be 4 digits.
  # @param page_num Page number of results to return, zero-indexed
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<Team>]
  describe 'get_teams_by_year test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_teams_by_year_keys
  # 
  # Gets a list Team Keys that competed in the given year, paginated in groups of 500.
  # @param year Competition Year (or Season). Must be 4 digits.
  # @param page_num Page number of results to return, zero-indexed
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<String>]
  describe 'get_teams_by_year_keys test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_teams_by_year_simple
  # 
  # Gets a list of short form &#x60;Team_Simple&#x60; objects that competed in the given year, paginated in groups of 500.
  # @param year Competition Year (or Season). Must be 4 digits.
  # @param page_num Page number of results to return, zero-indexed
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<TeamSimple>]
  describe 'get_teams_by_year_simple test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_teams_keys
  # 
  # Gets a list of Team keys, paginated in groups of 500. (Note, each page will not have 500 teams, but will include the teams within that range of 500.)
  # @param page_num Page number of results to return, zero-indexed
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<String>]
  describe 'get_teams_keys test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_teams_simple
  # 
  # Gets a list of short form &#x60;Team_Simple&#x60; objects, paginated in groups of 500.
  # @param page_num Page number of results to return, zero-indexed
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<TeamSimple>]
  describe 'get_teams_simple test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
