=begin
#The Blue Alliance API v3

## Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.

OpenAPI spec version: 3.03.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::MatchApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MatchApi' do
  before do
    # run before each test
    @instance = SwaggerClient::MatchApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MatchApi' do
    it 'should create an instance of MatchApi' do
      expect(@instance).to be_instance_of(SwaggerClient::MatchApi)
    end
  end

  # unit tests for get_event_match_timeseries
  # 
  # Gets an array of Match Keys for the given event key that have timeseries data. Returns an empty array if no matches have timeseries data. *WARNING:* This is *not* official data, and is subject to a significant possibility of error, or missing data. Do not rely on this data for any purpose. In fact, pretend we made it up. *WARNING:* This endpoint and corresponding data models are under *active development* and may change at any time, including in breaking ways.
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<String>]
  describe 'get_event_match_timeseries test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event_matches
  # 
  # Gets a list of matches for the given event.
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<Match>]
  describe 'get_event_matches test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event_matches_keys
  # 
  # Gets a list of match keys for the given event.
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<String>]
  describe 'get_event_matches_keys test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event_matches_simple
  # 
  # Gets a short-form list of matches for the given event.
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<MatchSimple>]
  describe 'get_event_matches_simple test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_match
  # 
  # Gets a &#x60;Match&#x60; object for the given match key.
  # @param match_key TBA Match Key, eg &#x60;2016nytr_qm1&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Match]
  describe 'get_match test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_match_simple
  # 
  # Gets a short-form &#x60;Match&#x60; object for the given match key.
  # @param match_key TBA Match Key, eg &#x60;2016nytr_qm1&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [MatchSimple]
  describe 'get_match_simple test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_match_timeseries
  # 
  # Gets an array of game-specific Match Timeseries objects for the given match key or an empty array if not available. *WARNING:* This is *not* official data, and is subject to a significant possibility of error, or missing data. Do not rely on this data for any purpose. In fact, pretend we made it up. *WARNING:* This endpoint and corresponding data models are under *active development* and may change at any time, including in breaking ways.
  # @param match_key TBA Match Key, eg &#x60;2016nytr_qm1&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<Object>]
  describe 'get_match_timeseries test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_team_event_matches
  # 
  # Gets a list of matches for the given team and event.
  # @param team_key TBA Team Key, eg &#x60;frc254&#x60;
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<Match>]
  describe 'get_team_event_matches test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_team_event_matches_keys
  # 
  # Gets a list of match keys for matches for the given team and event.
  # @param team_key TBA Team Key, eg &#x60;frc254&#x60;
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<String>]
  describe 'get_team_event_matches_keys test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_team_event_matches_simple
  # 
  # Gets a short-form list of matches for the given team and event.
  # @param team_key TBA Team Key, eg &#x60;frc254&#x60;
  # @param event_key TBA Event Key, eg &#x60;2016nytr&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<Match>]
  describe 'get_team_event_matches_simple test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_team_matches_by_year
  # 
  # Gets a list of matches for the given team and year.
  # @param team_key TBA Team Key, eg &#x60;frc254&#x60;
  # @param year Competition Year (or Season). Must be 4 digits.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<Match>]
  describe 'get_team_matches_by_year test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_team_matches_by_year_keys
  # 
  # Gets a list of match keys for matches for the given team and year.
  # @param team_key TBA Team Key, eg &#x60;frc254&#x60;
  # @param year Competition Year (or Season). Must be 4 digits.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<String>]
  describe 'get_team_matches_by_year_keys test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_team_matches_by_year_simple
  # 
  # Gets a short-form list of matches for the given team and year.
  # @param team_key TBA Team Key, eg &#x60;frc254&#x60;
  # @param year Competition Year (or Season). Must be 4 digits.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :if_modified_since Value of the &#x60;Last-Modified&#x60; header in the most recently cached response by the client.
  # @return [Array<MatchSimple>]
  describe 'get_team_matches_by_year_simple test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
