=begin
#The Blue Alliance API v3

## Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.

The version of the OpenAPI document: 3.8.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TBA API v3 Ruby Client::ZebraAlliances
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ZebraAlliances' do
  before do
    # run before each test
    @instance = TBA API v3 Ruby Client::ZebraAlliances.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ZebraAlliances' do
    it 'should create an instance of ZebraAlliances' do
      expect(@instance).to be_instance_of(TBA API v3 Ruby Client::ZebraAlliances)
    end
  end
  describe 'test attribute "red"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "blue"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
